FROM maven:3.6.3-openjdk-11 as builder
COPY ./settings.xml /root/.m2/
COPY . /src
WORKDIR /src
RUN mvn clean install

FROM adoptopenjdk/openjdk11:jdk-11.0.9.1_1-alpine
RUN apk --update add fontconfig ttf-dejavu
COPY --from=builder /src/target/template-manager*.jar template-manager.jar
EXPOSE 8080 8000 9999
ENTRYPOINT ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000", "-Dcom.sun.management.jmxremote=true", "-Dcom.sun.management.jmxremote.port=9999", "-Dcom.sun.management.jmxremote.authenticate=false", "-Dcom.sun.management.jmxremote.ssl=false", "-Djava.rmi.server.hostname=10.10.15.110", "-Dcom.sun.management.jmxremote.rmi.port=9999", "-jar", "template-manager.jar"]