version: '3'
services:
  #=========== BACKEND ===============      
  backend:
    container_name: backend
    image: ${REGISTRY}/${projectName}-${WORKING_ENV}:${RELEASE_VER}-${BUILD_NUMBER}
    ports:
      - "8080:8080"
    environment:
      - "DITO_MANAGER_FRONTEND_APP_BASE_URL=${hostIP}"
      - "SPRING_PROFILES_ACTIVE=dev"
      - "DITO_MANAGER_MAILING_ENABLE=true"
      - "DITO_MANAGER_SMTP_HOST=smtp.gmail.com"
      - "DITO_MANAGER_SMTP_PORT=587"
      - "DITO_MANAGER_SMTP_USERNAME=qatests006@gmail.com"
      - "DITO_MANAGER_SMTP_PASSWORD=Qwerty!123"
    depends_on:
      - db
  #=========== DATABASE ===============
  db:
    container_name: db
    image: ${REGISTRY}/${dbName}-${WORKING_ENV}:${RELEASE_VER}-${BUILD_NUMBER}
    ports:
      - "5432:5432"
