version: '3'
services:
  #=========== BACKEND ===============      
  backend:
    container_name: backend
    restart: always    
    image: ${REGISTRY}/${projectName}-${WORKING_ENV}:${RELEASE_VER}-${BUILD_NUMBER}
    environment:
      - GF_FRONTEND_APP_BASE_URL
      - DITO_MANAGER_FRONTEND_APP_BASE_URL
      - SPRING_PROFILES_ACTIVE
      - DITO_MANAGER_JWT_PRIVATE_KEY
      - DITO_MANAGER_ACCESS_TOKEN_TIME_TO_LIVE
      - DITO_MANAGER_REFRESH_TOKEN_TIME_TO_LIVE
      - DITO_MANAGER_MAXIMUM_FAILED_LOGIN_ATTEMPTS
      - DITO_MANAGER_CORS_ALLOWED_PATHS
      - DITO_MANAGER_CORS_ALLOWED_ORIGINS
      - DITO_MANAGER_CORS_ALLOWED_METHODS
      - DITO_MANAGER_DATABASE_URL
      - DITO_MANAGER_DATABASE_NAME
      - DITO_MANAGER_DATABASE_USERNAME
      - DITO_MANAGER_DATABASE_PASSWORD
      - DITO_MANAGER_MAILING_ENABLE
      - DITO_MANAGER_SMTP_HOST
      - DITO_MANAGER_SMTP_PORT
      - DITO_MANAGER_SMTP_USERNAME
      - DITO_MANAGER_SMTP_PASSWORD
      - DITO_MANAGER_SMTP_AUTH
      - DITO_MANAGER_SMTP_TLS_ENABLE
      - DITO_MANAGER_SENTRY_DSN
      - DITO_MANAGER_SENTRY_ENVIRONMENT
      - DITO_MANAGER_DEFAULT_ADMIN_EMAIL
      - DITO_MANAGER_DEFAULT_ADMIN_PASSWORD
    depends_on:
      - db
    ports:
      - "8000:8000"
      - "9999:9999"
  #=========== DATABASE ===============
  db:
    container_name: db
    restart: always
    image: ${REGISTRY}/${dbName}-${WORKING_ENV}:${RELEASE_VER}-${BUILD_NUMBER}
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB