version: '3'
services:
  #=========== BACKEND ===============      
  backend:
    container_name: backend
    image: ${REGISTRY}/${projectName}-${WORKING_ENV}:${RELEASE_VER}-${BUILD_NUMBER}
    ports:
      - "8080:8080"
    depends_on:
      - db
  #=========== DATABASE ===============
  db:
    container_name: db
    image: ${REGISTRY}/${dbName}-${WORKING_ENV}:${RELEASE_VER}-${BUILD_NUMBER}
    ports:
      - "5432:5432"

