version: '3'
services:
  #=========== BACKEND ===============      
  backend:
    container_name: backend
    image: ${REGISTRY}/${projectName}-${WORKING_ENV}:${RELEASE_VER}-${BUILD_NUMBER}
    environment:
      - GF_FRONTEND_APP_BASE_URL=frontend
      - DITO_MANAGER_FRONTEND_APP_BASE_URL=frontend
      - SPRING_PROFILES_ACTIVE=dev
      - DITO_MANAGER_MAILING_ENABLE=true
      - DITO_MANAGER_SMTP_HOST=${hostIP}
      - DITO_MANAGER_SMTP_PORT=1025
      - DITO_MANAGER_SMTP_USERNAME=user
      - DITO_MANAGER_SMTP_PASSWORD=pass
    ports:
      - "8080:8080"
    depends_on:
      - db
  #=========== DATABASE ===============
  db:
    container_name: db
    image: ${REGISTRY}/${dbName}-${WORKING_ENV}:${RELEASE_VER}-${BUILD_NUMBER}
    ports:
      - "5432:5432"

