version: '3.1'
services:
  dito-manager-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dito_manager_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345