security:
  jwt:
    id-alias: type
    private-key: pEBNLmtEX657LTgwgTR624GLy5qES3bH
    access-token:
      id: access
      time-to-live: 1800
    refresh-token:
      id: refresh
      time-to-live: 86400
    editor-token:
      id: editor
      time-to-live: 86400
    reset-password-token:
      id: resetPassword
      time-to-live: 86400
  login:
    failure:
      max-attempts: 5
  cors:
    paths: '/**'
    origins: '*'
    methods: '*'

spring:
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        default_schema: manager
  application:
    name: template-manager
  datasource:
    driver-class-name: org.postgresql.Driver
  liquibase:
    default-schema: manager
    change-log: classpath:db/changelog/db.changelog-master.xml
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  servlet:
    context-path: /api

resources:
  pictures:
    extensions:
      supported: bmp,ccit,gif,jpg,jpg2000,png,svg,wmf
    size-limit: 8388608
  stylesheets:
    extensions:
      supported: css
  fonts:
    extensions:
      supported: ttf

template:
  unblock-scheduler:
    execution-delay-in-millis: 3600000
    initial-delay-in-millis: 1000


data-collection:
  json:
      size-limit: 8388608

sentry:
  dsn: ${DITO_MANAGER_SENTRY_DSN:}
  environment: ${DITO_MANAGER_SENTRY_ENVIRONMENT:}