spring:
  datasource:
    url: jdbc:postgresql://<host>:<port>/dito
    username: <username>
    password: <password>

logging:
  level:
    com:
      itextpdf:
        dito:
          manager: debug