ditomanager:
  mailing:
    enabled: ${DITO_MANAGER_MAILING_ENABLE}

spring:
  datasource:
    url:  jdbc:postgresql://${DITO_MANAGER_DATABASE_URL}/${DITO_MANAGER_DATABASE_NAME}
    username: ${DITO_MANAGER_DATABASE_USERNAME}
    password: ${DITO_MANAGER_DATABASE_PASSWORD}
  mail:
    host: ${DITO_MANAGER_SMTP_HOST}
    port: ${DITO_MANAGER_SMTP_PORT}
    username: ${DITO_MANAGER_SMTP_USERNAME}
    password: ${DITO_MANAGER_SMTP_PASSWORD}
    front-redirect: ${DITO_MANAGER_FRONTEND_APP_BASE_URL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
