spring:
  application:
    name: template-manager
  datasource:
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml


server:
  servlet:
    context-api: /api
