security:
  cors:
    paths: '/**'
    origins: '*'
    methods: '*'

spring:
  datasource:
    url: jdbc:postgresql://db:5432/dito
    username: postgres
    password: 1111

logging:
  level:
    com:
      itextpdf:
        dito:
          manager: debug