ditomanager:
  mailing:
    enabled: ${DITO_MANAGER_MAILING_ENABLE}

spring:
  datasource:
    url: jdbc:postgresql://db:5432/dito
    username: postgres
    password: 1111
  mail:
    host: ${DITO_MANAGER_SMTP_HOST}
    port: ${DITO_MANAGER_SMTP_PORT}
    username: ${DITO_MANAGER_SMTP_USERNAME}
    password: ${DITO_MANAGER_SMTP_PASSWORD}
    front-redirect: ${DITO_MANAGER_FRONTEND_APP_BASE_URL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com:
      itextpdf:
        dito:
          manager: debug

jpa:
  properties:
    hibernate:
      show_sql: true
      format_sql: true