ditomanager:
  mailing:
    enabled: ${DITO_MANAGER_MAILING_ENABLE}

security:
  credentials:
    admin-email: ${DITO_MANAGER_DEFAULT_ADMIN_EMAIL:#{null}}
    admin-password: ${DITO_MANAGER_DEFAULT_ADMIN_PASSWORD:#{null}}

spring:
  datasource:
    url: jdbc:postgresql://db:5432/dito
    username: postgres
    password: 1111
  mail:
    host: ${DITO_MANAGER_SMTP_HOST}
    port: ${DITO_MANAGER_SMTP_PORT}
    username: ${DITO_MANAGER_SMTP_USERNAME}
    password: ${DITO_MANAGER_SMTP_PASSWORD}
    front-redirect: ${DITO_MANAGER_FRONTEND_APP_BASE_URL}
    privacy-information: ${DITO_MANAGER_PRIVACY_INFORMATION_APP_URL:https://itextpdf.com/en/how-buy/legal/privacy-policy}
    from: ${DITO_MANAGER_SMTP_FROM:${DITO_MANAGER_SMTP_USERNAME}}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com:
      itextpdf:
        dito:
          manager: debug

jpa:
  properties:
    hibernate:
      show_sql: true
      format_sql: true
