ditomanager:
  mailing:
    enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dito
    username: postgres
    password: postgres
  mail:
    host: in-v3.mailjet.com
    port: 587
    username: 67953d863646b958af96c16d770019b2
    password: ba29ac67832ca221913e4bbb46f0aec9
    front-redirect: 123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    liquibase: debug
    org:
      springframework:
        security: debug
    com:
      itextpdf:
        dito:
          manager: debug
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true