spring:
  datasource:
    url: jdbc:postgresql://db:5432/dito
    username: postgres
    password: 1111
  mail:
    host: smtp.gmail.com
    port: 465
    username: vadzim.sarokin.tech.acc@gmail.com
    password: 65[qXN?vq6k:fB$y
    front-redirect: ${GF_FRONTEND_APP_BASE_URL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com:
      itextpdf:
        dito:
          manager: debug