security:
  jwt:
    private-key: pEBNLmtEX657LTgwgTR624GLy5qES3bH
    access-token.time-to-live: 1800
    refresh-token.time-to-live: 86400

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dito
    username: postgres
    password: postgres

logging:
  level:
    liquibase: debug
    org:
      springframework:
        security: debug
    com:
      itextpdf:
        dito:
          manager: debug
