dito-manager:
  security:
    jwt-secret: 'JPLnpUx4KpRy3yU6'
    jwt-expiration-date: 86400

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dito
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345
  liquibase:
    default-schema: manager
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    liquibase: INFO
    org:
      springframework:
        security: DEBUG
    com:
      itextpdf:
        dito:
          manager: DEBUG
