security:
  jwt:
    private-key: ${DITO_MANAGER_JWT_PRIVATE_KEY}
    access-token:
      time-to-live: ${DITO_MANAGER_ACCESS_TOKEN_TIME_TO_LIVE}
    refresh-token:
      time-to-live: ${DITO_MANAGER_REFRESH_TOKEN_TIME_TO_LIVE}

spring:
  datasource:
    url: jdbc:postgresql://${DITO_MANAGER_DATABASE_URL}/{DITO_MANAGER_DATABASE_NAME}
    username: ${DITO_MANAGER_DATABASE_USERNAME}
    password: ${DITO_MANAGER_DATABASE_PASSWORD}