ditomanager:
  mailing:
    enabled: ${DITO_MANAGER_MAILING_ENABLE}

security:
  credentials:
    admin-email: ${DITO_MANAGER_DEFAULT_ADMIN_EMAIL:#{null}}
    admin-password: ${DITO_MANAGER_DEFAULT_ADMIN_PASSWORD:#{null}}

spring:
  datasource:
    url:  jdbc:postgresql://${DITO_MANAGER_DATABASE_URL}/${DITO_MANAGER_DATABASE_NAME}
    username: ${DITO_MANAGER_DATABASE_USERNAME}
    password: ${DITO_MANAGER_DATABASE_PASSWORD}
  mail:
    host: ${DITO_MANAGER_SMTP_HOST}
    port: ${DITO_MANAGER_SMTP_PORT}
    username: ${DITO_MANAGER_SMTP_USERNAME}
    password: ${DITO_MANAGER_SMTP_PASSWORD}
    front-redirect: ${DITO_MANAGER_FRONTEND_APP_BASE_URL}
    privacy-information: ${DITO_MANAGER_PRIVACY_INFORMATION_APP_URL:https://itextpdf.com/en/how-buy/legal/privacy-policy}
    from: ${DITO_MANAGER_SMTP_FROM:${DITO_MANAGER_SMTP_USERNAME}}
    properties:
      mail:
        smtp:
          auth: ${DITO_MANAGER_SMTP_AUTH:true}
          starttls:
            enable: ${DITO_MANAGER_SMTP_TLS_ENABLE:true}
