ditomanager:
  mailing:
    enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dito
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    front-redirect: 123
    privacy-information: 123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    liquibase: error
    org:
      hibernate:
        SQL: debug
        type: trace
      springframework:
        security: error
    com:
      itextpdf:
        dito:
          manager: debug
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
