security:
  jwt:
    private-key: ${DITO_MANAGER_JWT_PRIVATE_KEY}
    time-to-live: ${DITO_MANAGER_JWT_EXPIRATION_TIME}

spring:
  datasource:
    url: jdbc:postgresql://${DITO_MANAGER_DATABASE_URL}/{DITO_MANAGER_DATABASE_NAME}
    username: ${DITO_MANAGER_DATABASE_USERNAME}
    password: ${DITO_MANAGER_DATABASE_PASSWORD}