package com.itextpdf.dito.manager.dto.permission;

public class DataCollectionPermissionDTO {
    private String roleName;
    private String E6_US34_EDIT_DATA_COLLECTION_METADATA;
    private String E6_US35_CREATE_A_NEW_VERSION_OF_DATA_COLLECTION_USING_JSON;
    private String E6_US37_ROLL_BACK_OF_THE_DATA_COLLECTION;
    private String E6_US38_DELETE_DATA_COLLECTION;
    private String E7_US44_CREATE_NEW_DATA_SAMPLE_BASED_ON_JSON_FILE;
    private String E7_US47_EDIT_SAMPLE_METADATA;
    private String E7_US48_CREATE_NEW_VERSION_OF_DATA_SAMPLE;
    private String E7_US50_DELETE_DATA_SAMPLE;

    public DataCollectionPermissionDTO(String roleName, String e6_US34_EDIT_DATA_COLLECTION_METADATA, String e6_US35_CREATE_A_NEW_VERSION_OF_DATA_COLLECTION_USING_JSON, String e6_US37_ROLL_BACK_OF_THE_DATA_COLLECTION, String e6_US38_DELETE_DATA_COLLECTION, String e7_US44_CREATE_NEW_DATA_SAMPLE_BASED_ON_JSON_FILE,
                                       String e7_US47_EDIT_SAMPLE_METADATA, String e7_US48_CREATE_NEW_VERSION_OF_DATA_SAMPLE, String e7_US50_DELETE_DATA_SAMPLE) {
        this.roleName = roleName;
        E6_US34_EDIT_DATA_COLLECTION_METADATA = e6_US34_EDIT_DATA_COLLECTION_METADATA;
        E6_US35_CREATE_A_NEW_VERSION_OF_DATA_COLLECTION_USING_JSON = e6_US35_CREATE_A_NEW_VERSION_OF_DATA_COLLECTION_USING_JSON;
        E6_US37_ROLL_BACK_OF_THE_DATA_COLLECTION = e6_US37_ROLL_BACK_OF_THE_DATA_COLLECTION;
        E6_US38_DELETE_DATA_COLLECTION = e6_US38_DELETE_DATA_COLLECTION;
        E7_US44_CREATE_NEW_DATA_SAMPLE_BASED_ON_JSON_FILE = e7_US44_CREATE_NEW_DATA_SAMPLE_BASED_ON_JSON_FILE;
        E7_US47_EDIT_SAMPLE_METADATA = e7_US47_EDIT_SAMPLE_METADATA;
        E7_US48_CREATE_NEW_VERSION_OF_DATA_SAMPLE = e7_US48_CREATE_NEW_VERSION_OF_DATA_SAMPLE;
        E7_US50_DELETE_DATA_SAMPLE = e7_US50_DELETE_DATA_SAMPLE;
    }

    public DataCollectionPermissionDTO() {
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public String getE6_US34_EDIT_DATA_COLLECTION_METADATA() {
        return E6_US34_EDIT_DATA_COLLECTION_METADATA;
    }

    public void setE6_US34_EDIT_DATA_COLLECTION_METADATA(String e6_US34_EDIT_DATA_COLLECTION_METADATA) {
        E6_US34_EDIT_DATA_COLLECTION_METADATA = e6_US34_EDIT_DATA_COLLECTION_METADATA;
    }

    public String getE6_US35_CREATE_A_NEW_VERSION_OF_DATA_COLLECTION_USING_JSON() {
        return E6_US35_CREATE_A_NEW_VERSION_OF_DATA_COLLECTION_USING_JSON;
    }

    public void setE6_US35_CREATE_A_NEW_VERSION_OF_DATA_COLLECTION_USING_JSON(String e6_US35_CREATE_A_NEW_VERSION_OF_DATA_COLLECTION_USING_JSON) {
        E6_US35_CREATE_A_NEW_VERSION_OF_DATA_COLLECTION_USING_JSON = e6_US35_CREATE_A_NEW_VERSION_OF_DATA_COLLECTION_USING_JSON;
    }

    public String getE6_US37_ROLL_BACK_OF_THE_DATA_COLLECTION() {
        return E6_US37_ROLL_BACK_OF_THE_DATA_COLLECTION;
    }

    public void setE6_US37_ROLL_BACK_OF_THE_DATA_COLLECTION(String e6_US37_ROLL_BACK_OF_THE_DATA_COLLECTION) {
        E6_US37_ROLL_BACK_OF_THE_DATA_COLLECTION = e6_US37_ROLL_BACK_OF_THE_DATA_COLLECTION;
    }

    public String getE6_US38_DELETE_DATA_COLLECTION() {
        return E6_US38_DELETE_DATA_COLLECTION;
    }

    public void setE6_US38_DELETE_DATA_COLLECTION(String e6_US38_DELETE_DATA_COLLECTION) {
        E6_US38_DELETE_DATA_COLLECTION = e6_US38_DELETE_DATA_COLLECTION;
    }

    public String getE7_US44_CREATE_NEW_DATA_SAMPLE_BASED_ON_JSON_FILE() {
        return E7_US44_CREATE_NEW_DATA_SAMPLE_BASED_ON_JSON_FILE;
    }

    public void setE7_US44_CREATE_NEW_DATA_SAMPLE_BASED_ON_JSON_FILE(String e7_US44_CREATE_NEW_DATA_SAMPLE_BASED_ON_JSON_FILE) {
        E7_US44_CREATE_NEW_DATA_SAMPLE_BASED_ON_JSON_FILE = e7_US44_CREATE_NEW_DATA_SAMPLE_BASED_ON_JSON_FILE;
    }

    public String getE7_US47_EDIT_SAMPLE_METADATA() {
        return E7_US47_EDIT_SAMPLE_METADATA;
    }

    public void setE7_US47_EDIT_SAMPLE_METADATA(String e7_US47_EDIT_SAMPLE_METADATA) {
        E7_US47_EDIT_SAMPLE_METADATA = e7_US47_EDIT_SAMPLE_METADATA;
    }

    public String getE7_US48_CREATE_NEW_VERSION_OF_DATA_SAMPLE() {
        return E7_US48_CREATE_NEW_VERSION_OF_DATA_SAMPLE;
    }

    public void setE7_US48_CREATE_NEW_VERSION_OF_DATA_SAMPLE(String e7_US48_CREATE_NEW_VERSION_OF_DATA_SAMPLE) {
        E7_US48_CREATE_NEW_VERSION_OF_DATA_SAMPLE = e7_US48_CREATE_NEW_VERSION_OF_DATA_SAMPLE;
    }

    public String getE7_US50_DELETE_DATA_SAMPLE() {
        return E7_US50_DELETE_DATA_SAMPLE;
    }

    public void setE7_US50_DELETE_DATA_SAMPLE(String e7_US50_DELETE_DATA_SAMPLE) {
        E7_US50_DELETE_DATA_SAMPLE = e7_US50_DELETE_DATA_SAMPLE;
    }
}
