version: '3'
services:
  #=========== BACKEND ===============      
  backend:
    container_name: backend_itext
    image: nexus-docker.andersenlab.dev/${projectName}:${WORKING_ENV}
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
      - "DITO_MANAGER_MAILING_ENABLE=true"
    depends_on:
      - db
  #=========== DATABASE ===============
  db:
    container_name: db_itext
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - /root/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=dito
