version: '3'
services:
  #=========== BACKEND ===============      
  backend:
    container_name: backend 
    image: nexus-docker.andersenlab.dev/dtm-backend:dev
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    depends_on:
      - db
  #=========== DATABASE ===============
  db:
    container_name: db_itext
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ${WORKSPACE}/devops/ci/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=dito